### ISSUE TITLE
How to try it out?

### ISSUE THREAD

**Issue by pickfire** [roygbyte/gazette.koplugin#1]
Hi, I am not familiar with lua.

I tried koreader newsreader, but there is one site which does not seemed to work for me. https://www.sciencenet.cn/xml/blog.aspx?di=7, it works fine on flym (android) and akregator (linux)

flym works well (probably because it includes it's link by default on devices that uses chinese text) and display no extra unnecessary text

![Screenshot_20220722_220751](https://user-images.githubusercontent.com/4687791/180456684-389e85da-6b91-49dc-9053-f8e6a5211349.png)

![Screenshot_20220722_220806](https://user-images.githubusercontent.com/4687791/180456742-3ef9c2c2-1ddb-4e1d-8fee-5d4610314ad7.png)

akgregator shows extra unnecessary text

![image](https://user-images.githubusercontent.com/4687791/180456333-1c85b65f-a3c0-49ad-a515-ce7f63a5d4a7.png)

koreader does not even work, stuck while downloading

![Screenshot_20220722_220943](https://user-images.githubusercontent.com/4687791/180457062-f711b588-32a2-442c-8c73-eea7276625d7.png)

Yes, it does not seemed to pass https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fwww.sciencenet.cn%2Fxml%2Fblog.aspx%3Fdi%3D7 some rss check, but flym is still be able to work with it, not sure how

I wonder to try this out, but not quite sure how.

**Comment by roygbyte** [comment]
Hi! This plugin isn't ready for production, yet. 

Can you post the issue you're having in the [KOReader](http://GitHub.com/KOReader/koreader) repository instead?
